$(LIB_DIR)/%.a: \
$(OBJ_SINGLE_LINKED_LIST) \
$(OBJ_SINGLE_LINKED_LIST_COPY_TO_BUFFER) \
$(OBJ_SINGLE_LINKED_LIST_COPY_TO_NODE) \
$(OBJ_SINGLE_LINKED_LIST_INIT) \
$(OBJ_SINGLE_LINKED_LIST_PRINT_NODE_VALUE) \
$(OBJ_SINGLE_LINKED_LIST_SETUP_BUFFER_LENGTH) \
$(OBJ_SINGLE_LINKED_LIST_COMP_EQUAL) \
$(OBJ_SINGLE_LINKED_LIST_COMP_LESS) \
$(OBJ_SINGLE_LINKED_LIST_COMP_LESS_EQUAL) \
$(OBJ_SINGLE_LINKED_LIST_COMP_GREATER) \
$(OBJ_SINGLE_LINKED_LIST_COMP_GREATER_EQUAL)

		@mkdir -p $(LIB_DIR)
		ar -rc $@ $^


		