ROOT_DIR=../..

include $(ROOT_DIR)/Makefile.variable

LIB_NAME=cdll

ODIR_CIRCULAR_DOUBLE_LINKED_LIST=$(LIB_NAME)
ODIR:=$(ODIR)/$(ODIR_CIRCULAR_DOUBLE_LINKED_LIST)

_DEPS_CIRCULAR_DOUBLE_LINKED_LIST = circular_double_linked_list.h
DEPS_CIRCULAR_DOUBLE_LINKED_LIST = $(patsubst %,$(IDIR)/%,$(_DEPS_CIRCULAR_DOUBLE_LINKED_LIST))

_OBJ_CIRCULAR_DOUBLE_LINKED_LIST = push.o pop.o misc.o get_set.o
OBJ_CIRCULAR_DOUBLE_LINKED_LIST = $(patsubst %,$(ODIR)/%,$(_OBJ_CIRCULAR_DOUBLE_LINKED_LIST))

_OBJ_MAIN_CIRCULAR_DOUBLE_LINKED_LIST = cdll_test.o
OBJ_MAIN_CIRCULAR_DOUBLE_LINKED_LIST = $(patsubst %,$(ODIR)/%,$(_OBJ_MAIN_CIRCULAR_DOUBLE_LINKED_LIST))

_LIB_NAME = lib$(LIB_NAME).a
GEN_LIB_CIRCULAR_DOUBLE_LINKED_LIST = $(patsubst %,$(LIB_DIR)/%,$(_LIB_NAME))


$(ODIR)/%.o: %.c $(DEPS_CIRCULAR_DOUBLE_LINKED_LIST)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(LIB_DIR)/%.a: $(OBJ_CIRCULAR_DOUBLE_LINKED_LIST)
		@mkdir -p $(LIB_DIR)
		ar -rc $@ $^



CFLAGS := $(CFLAGS) -L$(LIB_DIR) -l$(LIB_NAME)