LIB_NAME=sll

ODIR_SINGLE_LINKED_LIST=$(LIB_NAME)
ODIR:=$(ODIR)/$(ODIR_SINGLE_LINKED_LIST)

ODIR_COPY_TO_BUFFER=$(ODIR)/$(SRC_COPY_TO_BUFFER)
ODIR_COPY_TO_NODE=$(ODIR)/$(SRC_COPY_TO_NODE)
ODIR_INIT=$(ODIR)/$(SRC_INIT)
ODIR_PRINT_NODE_VALUE=$(ODIR)/$(SRC_PRINT_NODE_VALUE)
ODIR_SETUP_BUFFER_LENGTH=$(ODIR)/$(SRC_SETUP_BUFFER_LENGTH)

ODIR_COMP=$(ODIR)/$(SRC_COMP)
ODIR_COMP_EQUAL=$(ODIR_COMP)/$(SRC_COMP_EQUAL)
ODIR_COMP_LESS=$(ODIR_COMP)/$(SRC_COMP_LESS)
ODIR_COMP_LESS_EQUAL=$(ODIR_COMP)/$(SRC_COMP_LESS_EQUAL)
ODIR_COMP_GREATER=$(ODIR_COMP)/$(SRC_COMP_GREATER)
ODIR_COMP_GREATER_EQUAL=$(ODIR_COMP)/$(SRC_COMP_GREATER_EQUAL)


_INCLUDE_SUB_DIR=sll
_INCLUDE_ROOT_DIR=$(_INCLUDE_SUB_DIR)/*.h
_INCLUDE_COPY_DIR=$(_INCLUDE_SUB_DIR)/copy/*.h
_INCLUDE_MISC_DIR=$(_INCLUDE_SUB_DIR)/misc/*.h
_INCLUDE_OPS_DIR=$(_INCLUDE_SUB_DIR)/ops/*.h


_OBJ_SINGLE_LINKED_LIST = push.o pop.o get_set.o print.o alloc_free.o setup_funcs.o search.o util.o append.o

_OBJ_SINGLE_LINKED_LIST_TYPE_FUNCTIONS = int.o float.o char.o pointer.o
_OBJ_SINGLE_LINKED_LIST_INIT_MAIN = init.o
_OBJ_SINGLE_LINKED_LIST_INIT_MAIN := $(_OBJ_SINGLE_LINKED_LIST_TYPE_FUNCTIONS) $(_OBJ_SINGLE_LINKED_LIST_INIT_MAIN)

_OBJ_MAIN_SINGLE_LINKED_LIST = ll_test.o

_LIB_NAME = lib$(LIB_NAME).a

CFLAGS := $(CFLAGS) -L$(LIB_DIR) -l$(LIB_NAME)

.PRECIOUS: $(ODIR)/%.o $(ODIR_COPY_TO_NODE)/%.o $(ODIR_COPY_TO_BUFFER)/%.o $(ODIR_INIT)/%.o $(ODIR_PRINT_NODE_VALUE)/%.o $(ODIR_SETUP_BUFFER_LENGTH)/%.o $(ODIR_COMP)/%.o
