INCLUDE_ROOT_DIR = $(patsubst %,$(DS_HEADER_PATH)/%,$(_INCLUDE_ROOT_DIR))
INCLUDE_COPY_DIR = $(patsubst %,$(DS_HEADER_PATH)/%,$(_INCLUDE_COPY_DIR))
INCLUDE_MISC_DIR = $(patsubst %,$(DS_HEADER_PATH)/%,$(_INCLUDE_MISC_DIR))
INCLUDE_OPS_DIR = $(patsubst %,$(DS_HEADER_PATH)/%,$(_INCLUDE_OPS_DIR))

INCLUDE_PREREQUISITE=$(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)


OBJ_SINGLE_LINKED_LIST = $(patsubst %,$(ODIR)/%,$(_OBJ_SINGLE_LINKED_LIST))

OBJ_SINGLE_LINKED_LIST_COPY_TO_NODE = $(patsubst %,$(ODIR_COPY_TO_NODE)/%,$(_OBJ_SINGLE_LINKED_LIST_TYPE_FUNCTIONS))
OBJ_SINGLE_LINKED_LIST_COPY_TO_BUFFER = $(patsubst %,$(ODIR_COPY_TO_BUFFER)/%,$(_OBJ_SINGLE_LINKED_LIST_TYPE_FUNCTIONS))
OBJ_SINGLE_LINKED_LIST_INIT = $(patsubst %,$(ODIR_INIT)/%,$(_OBJ_SINGLE_LINKED_LIST_INIT_MAIN))
OBJ_SINGLE_LINKED_LIST_PRINT_NODE_VALUE = $(patsubst %,$(ODIR_PRINT_NODE_VALUE)/%,$(_OBJ_SINGLE_LINKED_LIST_TYPE_FUNCTIONS))
OBJ_SINGLE_LINKED_LIST_SETUP_BUFFER_LENGTH = $(patsubst %,$(ODIR_SETUP_BUFFER_LENGTH)/%,$(_OBJ_SINGLE_LINKED_LIST_TYPE_FUNCTIONS))

OBJ_SINGLE_LINKED_LIST_COMP_EQUAL = $(patsubst %,$(ODIR_COMP_EQUAL)/%,$(_OBJ_SINGLE_LINKED_LIST_INIT_MAIN))
OBJ_SINGLE_LINKED_LIST_COMP_LESS = $(patsubst %,$(ODIR_COMP_LESS)/%,$(_OBJ_SINGLE_LINKED_LIST_INIT_MAIN))
OBJ_SINGLE_LINKED_LIST_COMP_LESS_EQUAL = $(patsubst %,$(ODIR_COMP_LESS_EQUAL)/%,$(_OBJ_SINGLE_LINKED_LIST_INIT_MAIN))
OBJ_SINGLE_LINKED_LIST_COMP_GREATER = $(patsubst %,$(ODIR_COMP_GREATER)/%,$(_OBJ_SINGLE_LINKED_LIST_INIT_MAIN))
OBJ_SINGLE_LINKED_LIST_COMP_GREATER_EQUAL = $(patsubst %,$(ODIR_COMP_GREATER_EQUAL)/%,$(_OBJ_SINGLE_LINKED_LIST_INIT_MAIN))

OBJ_MAIN_SINGLE_LINKED_LIST = $(patsubst %,$(ODIR)/%,$(_OBJ_MAIN_SINGLE_LINKED_LIST))


GEN_LIB_LINKED_LIST = $(patsubst %,$(LIB_DIR)/%,$(_LIB_NAME))
