$(ODIR)/%.o: %.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_COPY_TO_NODE)/%.o: $(SRC_COPY_TO_NODE)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_COPY_TO_BUFFER)/%.o: $(SRC_COPY_TO_BUFFER)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_INIT)/%.o: $(SRC_INIT)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)


$(ODIR_PRINT_NODE_VALUE)/%.o: $(SRC_PRINT_NODE_VALUE)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)


$(ODIR_SETUP_BUFFER_LENGTH)/%.o: $(SRC_SETUP_BUFFER_LENGTH)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)



$(ODIR_COMP_EQUAL)/%.o: $(SRC_COMP_EQUAL)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_COMP_LESS)/%.o: $(SRC_COMP_LESS)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_COMP_LESS_EQUAL)/%.o: $(SRC_COMP_LESS_EQUAL)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_COMP_GREATER)/%.o: $(SRC_COMP_GREATER)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_COMP_GREATER_EQUAL)/%.o: $(SRC_COMP_GREATER_EQUAL)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)



$(LIB_DIR)/%.a: \
$(OBJ_SINGLE_LINKED_LIST) \
$(OBJ_SINGLE_LINKED_LIST_COPY_TO_BUFFER) \
$(OBJ_SINGLE_LINKED_LIST_COPY_TO_NODE) \
$(OBJ_SINGLE_LINKED_LIST_INIT) \
$(OBJ_SINGLE_LINKED_LIST_PRINT_NODE_VALUE) \
$(OBJ_SINGLE_LINKED_LIST_SETUP_BUFFER_LENGTH) \
$(OBJ_SINGLE_LINKED_LIST_COMP_EQUAL) \
$(OBJ_SINGLE_LINKED_LIST_COMP_LESS) \
$(OBJ_SINGLE_LINKED_LIST_COMP_LESS_EQUAL) \
$(OBJ_SINGLE_LINKED_LIST_COMP_GREATER) \
$(OBJ_SINGLE_LINKED_LIST_COMP_GREATER_EQUAL)

		@mkdir -p $(LIB_DIR)
		ar -rc $@ $^





