ROOT_DIR=../..

include $(ROOT_DIR)/Makefile.variable

LIB_NAME=csll

ODIR_CSLL=$(LIB_NAME)
ODIR:=$(ODIR)/$(ODIR_CSLL)

ODIR_COPY_TO_BUFFER=$(ODIR)/$(SRC_COPY_TO_BUFFER)
ODIR_COPY_TO_NODE=$(ODIR)/$(SRC_COPY_TO_NODE)
ODIR_INIT=$(ODIR)/$(SRC_INIT)
ODIR_PRINT_NODE_VALUE=$(ODIR)/$(SRC_PRINT_NODE_VALUE)
ODIR_SETUP_BUFFER_LENGTH=$(ODIR)/$(SRC_SETUP_BUFFER_LENGTH)


_DEPS_CIRCULAR_SINGLE_LINKED_LIST = circular_single_linked_list.h
DEPS_CIRCULAR_SINGLE_LINKED_LIST = $(patsubst %,$(DS_HEADER_PATH)/%,$(_DEPS_CIRCULAR_SINGLE_LINKED_LIST))

_OBJ_CIRCULAR_SINGLE_LINKED_LIST = push.o pop.o get_set.o print.o alloc_free.o setup_funcs.o

_OBJ_CIRCULAR_SINGLE_LINKED_LIST_TYPE_FUNCTIONS = int.o float.o char.o pointer.o
_OBJ_CIRCULAR_SINGLE_LINKED_LIST_INIT_MAIN = init.o
_OBJ_CIRCULAR_SINGLE_LINKED_LIST_INIT_MAIN := $(_OBJ_CIRCULAR_SINGLE_LINKED_LIST_TYPE_FUNCTIONS) $(_OBJ_CIRCULAR_SINGLE_LINKED_LIST_INIT_MAIN)


_OBJ_MAIN_CIRCULAR_SINGLE_LINKED_LIST = csll_test.o

_LIB_NAME = lib$(LIB_NAME).a


OBJ_CIRCULAR_SINGLE_LINKED_LIST = $(patsubst %,$(ODIR)/%,$(_OBJ_CIRCULAR_SINGLE_LINKED_LIST))

OBJ_CIRCULAR_SINGLE_LINKED_LIST_COPY_TO_NODE = $(patsubst %,$(ODIR_COPY_TO_NODE)/%,$(_OBJ_CIRCULAR_SINGLE_LINKED_LIST_TYPE_FUNCTIONS))
OBJ_CIRCULAR_SINGLE_LINKED_LIST_COPY_TO_BUFFER = $(patsubst %,$(ODIR_COPY_TO_BUFFER)/%,$(_OBJ_CIRCULAR_SINGLE_LINKED_LIST_TYPE_FUNCTIONS))
OBJ_CIRCULAR_SINGLE_LINKED_LIST_INIT = $(patsubst %,$(ODIR_INIT)/%,$(_OBJ_CIRCULAR_SINGLE_LINKED_LIST_INIT_MAIN))
OBJ_CIRCULAR_SINGLE_LINKED_LIST_PRINT_NODE_VALUE = $(patsubst %,$(ODIR_PRINT_NODE_VALUE)/%,$(_OBJ_CIRCULAR_SINGLE_LINKED_LIST_TYPE_FUNCTIONS))
OBJ_CIRCULAR_SINGLE_LINKED_LIST_SETUP_BUFFER_LENGTH = $(patsubst %,$(ODIR_SETUP_BUFFER_LENGTH)/%,$(_OBJ_CIRCULAR_SINGLE_LINKED_LIST_TYPE_FUNCTIONS))


OBJ_MAIN_CIRCULAR_SINGLE_LINKED_LIST = $(patsubst %,$(ODIR)/%,$(_OBJ_MAIN_CIRCULAR_SINGLE_LINKED_LIST))

GEN_LIB_CIRCULAR_SINGLE_LINKED_LIST = $(patsubst %,$(LIB_DIR)/%,$(_LIB_NAME))


$(ODIR)/%.o: %.c $(DEPS_CIRCULAR_SINGLE_LINKED_LIST)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_COPY_TO_NODE)/%.o: $(SRC_COPY_TO_NODE)/%.c $(DEPS_SINGLE_LINKED_LIST)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_COPY_TO_BUFFER)/%.o: $(SRC_COPY_TO_BUFFER)/%.c $(DEPS_SINGLE_LINKED_LIST)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_INIT)/%.o: $(SRC_INIT)/%.c $(DEPS_SINGLE_LINKED_LIST)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)


$(ODIR_PRINT_NODE_VALUE)/%.o: $(SRC_PRINT_NODE_VALUE)/%.c $(DEPS_SINGLE_LINKED_LIST)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)


$(ODIR_SETUP_BUFFER_LENGTH)/%.o: $(SRC_SETUP_BUFFER_LENGTH)/%.c $(DEPS_SINGLE_LINKED_LIST)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(LIB_DIR)/$(_LIB_NAME): $(OBJ_CIRCULAR_SINGLE_LINKED_LIST) $(OBJ_CIRCULAR_SINGLE_LINKED_LIST_COPY_TO_BUFFER) $(OBJ_CIRCULAR_SINGLE_LINKED_LIST_COPY_TO_NODE) $(OBJ_CIRCULAR_SINGLE_LINKED_LIST_INIT) $(OBJ_CIRCULAR_SINGLE_LINKED_LIST_PRINT_NODE_VALUE) $(OBJ_CIRCULAR_SINGLE_LINKED_LIST_SETUP_BUFFER_LENGTH)
		@mkdir -p $(LIB_DIR)
		ar -rc $@ $^

CFLAGS := $(CFLAGS) -L$(LIB_DIR) -l$(LIB_NAME)