ROOT_DIR=../..

include $(ROOT_DIR)/Makefile.variable

LIB_NAME=sll

ODIR_SINGLE_LINKED_LIST=$(LIB_NAME)
ODIR:=$(ODIR)/$(ODIR_SINGLE_LINKED_LIST)

ODIR_COPY_TO_BUFFER=$(ODIR)/$(SRC_COPY_TO_BUFFER)
ODIR_COPY_TO_NODE=$(ODIR)/$(SRC_COPY_TO_NODE)
ODIR_INIT=$(ODIR)/$(SRC_INIT)
ODIR_PRINT_NODE_VALUE=$(ODIR)/$(SRC_PRINT_NODE_VALUE)
ODIR_SETUP_BUFFER_LENGTH=$(ODIR)/$(SRC_SETUP_BUFFER_LENGTH)
ODIR_COMP=$(ODIR)/$(SRC_COMP)


_INCLUDE_SUB_DIR=sll
_INCLUDE_ROOT_DIR=$(_INCLUDE_SUB_DIR)/*.h
_INCLUDE_COPY_DIR=$(_INCLUDE_SUB_DIR)/copy/*.h
_INCLUDE_MISC_DIR=$(_INCLUDE_SUB_DIR)/misc/*.h
_INCLUDE_OPS_DIR=$(_INCLUDE_SUB_DIR)/ops/*.h


# Include files recipe
INCLUDE_ROOT_DIR = $(patsubst %,$(DS_HEADER_PATH)/%,$(_INCLUDE_ROOT_DIR))
INCLUDE_COPY_DIR = $(patsubst %,$(DS_HEADER_PATH)/%,$(_INCLUDE_COPY_DIR))
INCLUDE_MISC_DIR = $(patsubst %,$(DS_HEADER_PATH)/%,$(_INCLUDE_MISC_DIR))
INCLUDE_OPS_DIR = $(patsubst %,$(DS_HEADER_PATH)/%,$(_INCLUDE_OPS_DIR))

# Single Linked List objects recipes
_OBJ_SINGLE_LINKED_LIST = push.o pop.o get_set.o print.o alloc_free.o setup_funcs.o search.o util.o append.o

_OBJ_SINGLE_LINKED_LIST_TYPE_FUNCTIONS = int.o float.o char.o pointer.o
_OBJ_SINGLE_LINKED_LIST_COMP_FUNCTIONS = less.o greater.o equal.o
_OBJ_SINGLE_LINKED_LIST_INIT_MAIN = init.o
_OBJ_SINGLE_LINKED_LIST_INIT_MAIN := $(_OBJ_SINGLE_LINKED_LIST_TYPE_FUNCTIONS) $(_OBJ_SINGLE_LINKED_LIST_INIT_MAIN)

_OBJ_MAIN_SINGLE_LINKED_LIST = ll_test.o

OBJ_SINGLE_LINKED_LIST = $(patsubst %,$(ODIR)/%,$(_OBJ_SINGLE_LINKED_LIST))

OBJ_SINGLE_LINKED_LIST_COPY_TO_NODE = $(patsubst %,$(ODIR_COPY_TO_NODE)/%,$(_OBJ_SINGLE_LINKED_LIST_TYPE_FUNCTIONS))
OBJ_SINGLE_LINKED_LIST_COPY_TO_BUFFER = $(patsubst %,$(ODIR_COPY_TO_BUFFER)/%,$(_OBJ_SINGLE_LINKED_LIST_TYPE_FUNCTIONS))
OBJ_SINGLE_LINKED_LIST_INIT = $(patsubst %,$(ODIR_INIT)/%,$(_OBJ_SINGLE_LINKED_LIST_INIT_MAIN))
OBJ_SINGLE_LINKED_LIST_PRINT_NODE_VALUE = $(patsubst %,$(ODIR_PRINT_NODE_VALUE)/%,$(_OBJ_SINGLE_LINKED_LIST_TYPE_FUNCTIONS))
OBJ_SINGLE_LINKED_LIST_SETUP_BUFFER_LENGTH = $(patsubst %,$(ODIR_SETUP_BUFFER_LENGTH)/%,$(_OBJ_SINGLE_LINKED_LIST_TYPE_FUNCTIONS))
OBJ_SINGLE_LINKED_LIST_COMP = $(patsubst %,$(ODIR_COMP)/%,$(_OBJ_SINGLE_LINKED_LIST_COMP_FUNCTIONS))

OBJ_MAIN_SINGLE_LINKED_LIST = $(patsubst %,$(ODIR)/%,$(_OBJ_MAIN_SINGLE_LINKED_LIST))


_LIB_NAME = lib$(LIB_NAME).a
GEN_LIB_LINKED_LIST = $(patsubst %,$(LIB_DIR)/%,$(_LIB_NAME))

$(ODIR)/%.o: %.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_COPY_TO_NODE)/%.o: $(SRC_COPY_TO_NODE)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_COPY_TO_BUFFER)/%.o: $(SRC_COPY_TO_BUFFER)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_INIT)/%.o: $(SRC_INIT)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)


$(ODIR_PRINT_NODE_VALUE)/%.o: $(SRC_PRINT_NODE_VALUE)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)


$(ODIR_SETUP_BUFFER_LENGTH)/%.o: $(SRC_SETUP_BUFFER_LENGTH)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(ODIR_COMP)/%.o: $(SRC_COMP)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)


$(ODIR_COMP)/%.o: $(SRC_COMP)/%.c $(INCLUDE_ROOT_DIR) $(INCLUDE_COPY_DIR) $(INCLUDE_MISC_DIR) $(INCLUDE_OPS_DIR)
		@mkdir -p $(@D)
		$(CC) -g -c -o $@ $< $(CFLAGS)

$(LIB_DIR)/%.a: $(OBJ_SINGLE_LINKED_LIST) $(OBJ_SINGLE_LINKED_LIST_COPY_TO_BUFFER) $(OBJ_SINGLE_LINKED_LIST_COPY_TO_NODE) $(OBJ_SINGLE_LINKED_LIST_INIT) $(OBJ_SINGLE_LINKED_LIST_PRINT_NODE_VALUE) $(OBJ_SINGLE_LINKED_LIST_SETUP_BUFFER_LENGTH) $(OBJ_SINGLE_LINKED_LIST_COMP)
		@mkdir -p $(LIB_DIR)
		ar -rc $@ $^


CFLAGS := $(CFLAGS) -L$(LIB_DIR) -l$(LIB_NAME)
